name: ssec-scipy2024
channels:
  - conda-forge
  - defaults
dependencies:
  - ai2-olmo
  - fsspec
  - gcsfs
  - huggingface_hub
  - ipykernel
  - ipywidgets
  - jupyter-book
  - jupyterlab
  - pandas
  - pytorch
  - python=3.11
  - qdrant-client
  - sentence-transformers
  - sphinx-codeautolink
  - sphinx-exercise
  - sphinx-notfound-page
  - sphinxext-rediraffe
  - tqdm
  - transformers<4.39
  - pip
  - pip:
    - qdrant-client